name: If Statements Workflow Example
on: push

env:
  NAME: "Rofhiwa"
  AGE: 28
  GENDER: "Male"
  QUALIFIES: true

jobs:
  user-information-communicator:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the guest.
        run: echo "Greetings $NAME, and welcome to GitHub Actions workflow info emitter."

