name: Node Scripts Actions Workflow Example
on:
  push:
    paths:
      - "node-scripts-trigger/*"
jobs:
  install-node-packages-and-run-the-random-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd node-scripts-trigger
      - run: npm install
      - run: node script.js

